menu:
  Home: /
  Archives: /archives

widgets:
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid: false
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: false

google_analytics:
rss: